# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RaspPiReader/qt/about.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_aboutDialog(object):
    def setupUi(self, aboutDialog):
        aboutDialog.setObjectName("aboutDialog")
        aboutDialog.resize(262, 110)
        self.label = QtWidgets.QLabel(aboutDialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 221, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(aboutDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 221, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(aboutDialog)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 51, 17))
        self.label_3.setObjectName("label_3")
        self.labelDoctorPlc = QtWidgets.QLabel(aboutDialog)
        self.labelDoctorPlc.setGeometry(QtCore.QRect(70, 50, 61, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.labelDoctorPlc.setFont(font)
        self.labelDoctorPlc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelDoctorPlc.setStyleSheet("color: rgb(0, 85, 255);")
        self.labelDoctorPlc.setObjectName("labelDoctorPlc")
        self.label_4 = QtWidgets.QLabel(aboutDialog)
        self.label_4.setGeometry(QtCore.QRect(140, 50, 111, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(aboutDialog)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 71, 17))
        self.label_5.setObjectName("label_5")
        self.labelDoctorPlc_2 = QtWidgets.QLabel(aboutDialog)
        self.labelDoctorPlc_2.setGeometry(QtCore.QRect(90, 70, 121, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.labelDoctorPlc_2.setFont(font)
        self.labelDoctorPlc_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelDoctorPlc_2.setStyleSheet("color: rgb(0, 85, 255);")
        self.labelDoctorPlc_2.setObjectName("labelDoctorPlc_2")

        self.retranslateUi(aboutDialog)
        QtCore.QMetaObject.connectSlotsByName(aboutDialog)

    def retranslateUi(self, aboutDialog):
        _translate = QtCore.QCoreApplication.translate
        aboutDialog.setWindowTitle(_translate("aboutDialog", "About"))
        self.label.setText(_translate("aboutDialog", "License to : ST@PTM"))
        self.label_2.setText(_translate("aboutDialog", "Modbus Tech V1.0"))
        self.label_3.setText(_translate("aboutDialog", " Ⓒ 2021"))
        self.labelDoctorPlc.setText(_translate("aboutDialog", "doctorPLC"))
        self.label_4.setText(_translate("aboutDialog", "All Right Reserved"))
        self.label_5.setText(_translate("aboutDialog", "Visit us at :"))
        self.labelDoctorPlc_2.setText(_translate("aboutDialog", "www.doctorplc.com"))
