# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boolean_status.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BooleanStatusWidget(object):
    def setupUi(self, BooleanStatusWidget):
        BooleanStatusWidget.setObjectName("BooleanStatusWidget")
        BooleanStatusWidget.resize(300, 150)
        self.verticalLayout = QtWidgets.QVBoxLayout(BooleanStatusWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.boolStatusLabel1 = QtWidgets.QLabel(BooleanStatusWidget)
        self.boolStatusLabel1.setObjectName("boolStatusLabel1")
        self.verticalLayout.addWidget(self.boolStatusLabel1)
        self.boolStatusLabel2 = QtWidgets.QLabel(BooleanStatusWidget)
        self.boolStatusLabel2.setObjectName("boolStatusLabel2")
        self.verticalLayout.addWidget(self.boolStatusLabel2)
        self.boolStatusLabel3 = QtWidgets.QLabel(BooleanStatusWidget)
        self.boolStatusLabel3.setObjectName("boolStatusLabel3")
        self.verticalLayout.addWidget(self.boolStatusLabel3)
        self.boolStatusLabel4 = QtWidgets.QLabel(BooleanStatusWidget)
        self.boolStatusLabel4.setObjectName("boolStatusLabel4")
        self.verticalLayout.addWidget(self.boolStatusLabel4)
        self.boolStatusLabel5 = QtWidgets.QLabel(BooleanStatusWidget)
        self.boolStatusLabel5.setObjectName("boolStatusLabel5")
        self.verticalLayout.addWidget(self.boolStatusLabel5)
        self.boolStatusLabel6 = QtWidgets.QLabel(BooleanStatusWidget)
        self.boolStatusLabel6.setObjectName("boolStatusLabel6")
        self.verticalLayout.addWidget(self.boolStatusLabel6)

        self.retranslateUi(BooleanStatusWidget)
        QtCore.QMetaObject.connectSlotsByName(BooleanStatusWidget)

    def retranslateUi(self, BooleanStatusWidget):
        _translate = QtCore.QCoreApplication.translate
        self.boolStatusLabel1.setText(_translate("BooleanStatusWidget", "Bool Addr 1101: Not updated"))
        self.boolStatusLabel2.setText(_translate("BooleanStatusWidget", "Bool Addr 1102: Not updated"))
        self.boolStatusLabel3.setText(_translate("BooleanStatusWidget", "Bool Addr 1103: Not updated"))
        self.boolStatusLabel4.setText(_translate("BooleanStatusWidget", "Bool Addr 1104: Not updated"))
        self.boolStatusLabel5.setText(_translate("BooleanStatusWidget", "Bool Addr 1105: Not updated"))
        self.boolStatusLabel6.setText(_translate("BooleanStatusWidget", "Bool Addr 1106: Not updated"))
