# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\DEV\Python\PLC Integration\src1-main\src1-main\RaspPiReader-master\RaspPiReader\qt\boolean_data_display.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BooleanDataDisplay(object):
    def setupUi(self, BooleanDataDisplay):
        BooleanDataDisplay.setObjectName("BooleanDataDisplay")
        BooleanDataDisplay.resize(400, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(BooleanDataDisplay)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_1 = QtWidgets.QLabel(BooleanDataDisplay)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.value_1 = QtWidgets.QLabel(BooleanDataDisplay)
        self.value_1.setObjectName("value_1")
        self.gridLayout.addWidget(self.value_1, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(BooleanDataDisplay)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.value_2 = QtWidgets.QLabel(BooleanDataDisplay)
        self.value_2.setObjectName("value_2")
        self.gridLayout.addWidget(self.value_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(BooleanDataDisplay)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.value_3 = QtWidgets.QLabel(BooleanDataDisplay)
        self.value_3.setObjectName("value_3")
        self.gridLayout.addWidget(self.value_3, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(BooleanDataDisplay)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.value_4 = QtWidgets.QLabel(BooleanDataDisplay)
        self.value_4.setObjectName("value_4")
        self.gridLayout.addWidget(self.value_4, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(BooleanDataDisplay)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.value_5 = QtWidgets.QLabel(BooleanDataDisplay)
        self.value_5.setObjectName("value_5")
        self.gridLayout.addWidget(self.value_5, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(BooleanDataDisplay)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.value_6 = QtWidgets.QLabel(BooleanDataDisplay)
        self.value_6.setObjectName("value_6")
        self.gridLayout.addWidget(self.value_6, 5, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(BooleanDataDisplay)
        QtCore.QMetaObject.connectSlotsByName(BooleanDataDisplay)

    def retranslateUi(self, BooleanDataDisplay):
        _translate = QtCore.QCoreApplication.translate
        BooleanDataDisplay.setWindowTitle(_translate("BooleanDataDisplay", "Boolean Data"))
        self.label_1.setText(_translate("BooleanDataDisplay", "Label 1:"))
        self.value_1.setText(_translate("BooleanDataDisplay", "False"))
        self.label_2.setText(_translate("BooleanDataDisplay", "Label 2:"))
        self.value_2.setText(_translate("BooleanDataDisplay", "False"))
        self.label_3.setText(_translate("BooleanDataDisplay", "Label 3:"))
        self.value_3.setText(_translate("BooleanDataDisplay", "False"))
        self.label_4.setText(_translate("BooleanDataDisplay", "Label 4:"))
        self.value_4.setText(_translate("BooleanDataDisplay", "False"))
        self.label_5.setText(_translate("BooleanDataDisplay", "Label 5:"))
        self.value_5.setText(_translate("BooleanDataDisplay", "False"))
        self.label_6.setText(_translate("BooleanDataDisplay", "Label 6:"))
        self.value_6.setText(_translate("BooleanDataDisplay", "False"))
