# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RaspPiReader/qt/database_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DatabaseSettingsDialog(object):
    def setupUi(self, DatabaseSettingsDialog):
        DatabaseSettingsDialog.setObjectName("DatabaseSettingsDialog")
        DatabaseSettingsDialog.resize(400, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(DatabaseSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.usernameLabel = QtWidgets.QLabel(DatabaseSettingsDialog)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(DatabaseSettingsDialog)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameLineEdit)
        self.passwordLabel = QtWidgets.QLabel(DatabaseSettingsDialog)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(DatabaseSettingsDialog)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        self.serverLabel = QtWidgets.QLabel(DatabaseSettingsDialog)
        self.serverLabel.setObjectName("serverLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.serverLabel)
        self.serverLineEdit = QtWidgets.QLineEdit(DatabaseSettingsDialog)
        self.serverLineEdit.setObjectName("serverLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.serverLineEdit)
        self.databaseLabel = QtWidgets.QLabel(DatabaseSettingsDialog)
        self.databaseLabel.setObjectName("databaseLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.databaseLabel)
        self.databaseLineEdit = QtWidgets.QLineEdit(DatabaseSettingsDialog)
        self.databaseLineEdit.setObjectName("databaseLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.databaseLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.testConnectionPushButton = QtWidgets.QPushButton(DatabaseSettingsDialog)
        self.testConnectionPushButton.setObjectName("testConnectionPushButton")
        self.buttonLayout.addWidget(self.testConnectionPushButton)
        self.savePushButton = QtWidgets.QPushButton(DatabaseSettingsDialog)
        self.savePushButton.setObjectName("savePushButton")
        self.buttonLayout.addWidget(self.savePushButton)
        self.cancelPushButton = QtWidgets.QPushButton(DatabaseSettingsDialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.buttonLayout.addWidget(self.cancelPushButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(DatabaseSettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(DatabaseSettingsDialog)

    def retranslateUi(self, DatabaseSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        DatabaseSettingsDialog.setWindowTitle(_translate("DatabaseSettingsDialog", "Database Settings"))
        self.usernameLabel.setText(_translate("DatabaseSettingsDialog", "Username:"))
        self.passwordLabel.setText(_translate("DatabaseSettingsDialog", "Password:"))
        self.serverLabel.setText(_translate("DatabaseSettingsDialog", "Server:"))
        self.databaseLabel.setText(_translate("DatabaseSettingsDialog", "Database:"))
        self.testConnectionPushButton.setText(_translate("DatabaseSettingsDialog", "Test Connection"))
        self.savePushButton.setText(_translate("DatabaseSettingsDialog", "Save"))
        self.cancelPushButton.setText(_translate("DatabaseSettingsDialog", "Cancel"))
