# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\DEV\Python\PLC Integration\src1-main\src1-main\RaspPiReader-master\RaspPiReader\qt\duplicate_password_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DuplicatePasswordDialog(object):
    def setupUi(self, DuplicatePasswordDialog):
        DuplicatePasswordDialog.setObjectName("DuplicatePasswordDialog")
        self.verticalLayout = QtWidgets.QVBoxLayout(DuplicatePasswordDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.instructionLabel = QtWidgets.QLabel(DuplicatePasswordDialog)
        self.instructionLabel.setObjectName("instructionLabel")
        self.verticalLayout.addWidget(self.instructionLabel)
        self.duplicateList = QtWidgets.QTextBrowser(DuplicatePasswordDialog)
        self.duplicateList.setObjectName("duplicateList")
        self.verticalLayout.addWidget(self.duplicateList)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.supervisorUsernameLabel = QtWidgets.QLabel(DuplicatePasswordDialog)
        self.supervisorUsernameLabel.setObjectName("supervisorUsernameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.supervisorUsernameLabel)
        self.supervisorUsernameLineEdit = QtWidgets.QLineEdit(DuplicatePasswordDialog)
        self.supervisorUsernameLineEdit.setObjectName("supervisorUsernameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.supervisorUsernameLineEdit)
        self.supervisorPasswordLabel = QtWidgets.QLabel(DuplicatePasswordDialog)
        self.supervisorPasswordLabel.setObjectName("supervisorPasswordLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.supervisorPasswordLabel)
        self.supervisorPasswordLineEdit = QtWidgets.QLineEdit(DuplicatePasswordDialog)
        self.supervisorPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.supervisorPasswordLineEdit.setObjectName("supervisorPasswordLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.supervisorPasswordLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.okButton = QtWidgets.QPushButton(DuplicatePasswordDialog)
        self.okButton.setObjectName("okButton")
        self.buttonLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(DuplicatePasswordDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(DuplicatePasswordDialog)
        QtCore.QMetaObject.connectSlotsByName(DuplicatePasswordDialog)

    def retranslateUi(self, DuplicatePasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        DuplicatePasswordDialog.setWindowTitle(_translate("DuplicatePasswordDialog", "Duplicate Serial Authorization"))
        self.instructionLabel.setText(_translate("DuplicatePasswordDialog", "The following serial numbers already exist in the system:"))
        self.supervisorUsernameLabel.setText(_translate("DuplicatePasswordDialog", "Supervisor Username:"))
        self.supervisorPasswordLabel.setText(_translate("DuplicatePasswordDialog", "Supervisor Password:"))
        self.okButton.setText(_translate("DuplicatePasswordDialog", "OK"))
        self.cancelButton.setText(_translate("DuplicatePasswordDialog", "Cancel"))
