# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RaspPiReader/qt\new_cycle.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewCycle(object):
    def setupUi(self, NewCycle):
        NewCycle.setObjectName("NewCycle")
        NewCycle.resize(400, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewCycle)
        self.verticalLayout.setObjectName("verticalLayout")
        self.startCycleButton = QtWidgets.QPushButton(NewCycle)
        self.startCycleButton.setObjectName("startCycleButton")
        self.verticalLayout.addWidget(self.startCycleButton)
        self.stopCycleButton = QtWidgets.QPushButton(NewCycle)
        self.stopCycleButton.setObjectName("stopCycleButton")
        self.verticalLayout.addWidget(self.stopCycleButton)

        self.retranslateUi(NewCycle)
        QtCore.QMetaObject.connectSlotsByName(NewCycle)

    def retranslateUi(self, NewCycle):
        _translate = QtCore.QCoreApplication.translate
        NewCycle.setWindowTitle(_translate("NewCycle", "New Cycle"))
        self.startCycleButton.setText(_translate("NewCycle", "Start Cycle"))
        self.startCycleButton.setStyleSheet(_translate("NewCycle", "background-color: green; color: white;"))
        self.stopCycleButton.setText(_translate("NewCycle", "Stop Cycle"))
        self.stopCycleButton.setStyleSheet(_translate("NewCycle", "background-color: red; color: white;"))
