# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RaspPiReader/qt/one_drive_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OneDriveSettingsDialog(object):
    def setupUi(self, OneDriveSettingsDialog):
        OneDriveSettingsDialog.setObjectName("OneDriveSettingsDialog")
        OneDriveSettingsDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(OneDriveSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.clientIdLabel = QtWidgets.QLabel(OneDriveSettingsDialog)
        self.clientIdLabel.setObjectName("clientIdLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.clientIdLabel)
        self.clientIdLineEdit = QtWidgets.QLineEdit(OneDriveSettingsDialog)
        self.clientIdLineEdit.setObjectName("clientIdLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.clientIdLineEdit)
        self.clientSecretLabel = QtWidgets.QLabel(OneDriveSettingsDialog)
        self.clientSecretLabel.setObjectName("clientSecretLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.clientSecretLabel)
        self.clientSecretLineEdit = QtWidgets.QLineEdit(OneDriveSettingsDialog)
        self.clientSecretLineEdit.setObjectName("clientSecretLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.clientSecretLineEdit)
        self.tenantIdLabel = QtWidgets.QLabel(OneDriveSettingsDialog)
        self.tenantIdLabel.setObjectName("tenantIdLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.tenantIdLabel)
        self.tenantIdLineEdit = QtWidgets.QLineEdit(OneDriveSettingsDialog)
        self.tenantIdLineEdit.setObjectName("tenantIdLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tenantIdLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.testConnectionPushButton = QtWidgets.QPushButton(OneDriveSettingsDialog)
        self.testConnectionPushButton.setObjectName("testConnectionPushButton")
        self.buttonLayout.addWidget(self.testConnectionPushButton)
        self.savePushButton = QtWidgets.QPushButton(OneDriveSettingsDialog)
        self.savePushButton.setObjectName("savePushButton")
        self.buttonLayout.addWidget(self.savePushButton)
        self.cancelPushButton = QtWidgets.QPushButton(OneDriveSettingsDialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.buttonLayout.addWidget(self.cancelPushButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(OneDriveSettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(OneDriveSettingsDialog)

    def retranslateUi(self, OneDriveSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        OneDriveSettingsDialog.setWindowTitle(_translate("OneDriveSettingsDialog", "OneDrive Settings"))
        self.clientIdLabel.setText(_translate("OneDriveSettingsDialog", "Client ID:"))
        self.clientSecretLabel.setText(_translate("OneDriveSettingsDialog", "Client Secret:"))
        self.tenantIdLabel.setText(_translate("OneDriveSettingsDialog", "Tenant ID:"))
        self.testConnectionPushButton.setText(_translate("OneDriveSettingsDialog", "Test Connection"))
        self.savePushButton.setText(_translate("OneDriveSettingsDialog", "Save"))
        self.cancelPushButton.setText(_translate("OneDriveSettingsDialog", "Cancel"))
