# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RaspPiReader/qt/plc_comm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PLCCommSettingsDialog(object):
    def setupUi(self, PLCCommSettingsDialog):
        PLCCommSettingsDialog.setObjectName("PLCCommSettingsDialog")
        PLCCommSettingsDialog.resize(400, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(PLCCommSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.commModeLabel = QtWidgets.QLabel(PLCCommSettingsDialog)
        self.commModeLabel.setObjectName("commModeLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.commModeLabel)
        self.commModeComboBox = QtWidgets.QComboBox(PLCCommSettingsDialog)
        self.commModeComboBox.setObjectName("commModeComboBox")
        self.commModeComboBox.addItem("")
        self.commModeComboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.commModeComboBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.savePushButton = QtWidgets.QPushButton(PLCCommSettingsDialog)
        self.savePushButton.setObjectName("savePushButton")
        self.buttonLayout.addWidget(self.savePushButton)
        self.cancelPushButton = QtWidgets.QPushButton(PLCCommSettingsDialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.buttonLayout.addWidget(self.cancelPushButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(PLCCommSettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(PLCCommSettingsDialog)

    def retranslateUi(self, PLCCommSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        PLCCommSettingsDialog.setWindowTitle(_translate("PLCCommSettingsDialog", "PLC Communication Settings"))
        self.commModeLabel.setText(_translate("PLCCommSettingsDialog", "Communication Mode:"))
        self.commModeComboBox.setItemText(0, _translate("PLCCommSettingsDialog", "RS485"))
        self.commModeComboBox.setItemText(1, _translate("PLCCommSettingsDialog", "TCP"))
        self.savePushButton.setText(_translate("PLCCommSettingsDialog", "Save"))
        self.cancelPushButton.setText(_translate("PLCCommSettingsDialog", "Cancel"))
