# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plc_comm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PLCCommSettingsDialog(object):
    def setupUi(self, PLCCommSettingsDialog):
        PLCCommSettingsDialog.setObjectName("PLCCommSettingsDialog")
        PLCCommSettingsDialog.resize(400, 250)
        self.verticalLayout = QtWidgets.QVBoxLayout(PLCCommSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.commModeLabel = QtWidgets.QLabel(PLCCommSettingsDialog)
        self.commModeLabel.setObjectName("commModeLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.commModeLabel)
        self.commModeComboBox = QtWidgets.QComboBox(PLCCommSettingsDialog)
        self.commModeComboBox.setObjectName("commModeComboBox")
        self.commModeComboBox.addItem("")
        self.commModeComboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.commModeComboBox)
        self.ipLabel = QtWidgets.QLabel(PLCCommSettingsDialog)
        self.ipLabel.setObjectName("ipLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ipLabel)
        self.ipLineEdit = QtWidgets.QLineEdit(PLCCommSettingsDialog)
        self.ipLineEdit.setObjectName("ipLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ipLineEdit)
        self.portLabel = QtWidgets.QLabel(PLCCommSettingsDialog)
        self.portLabel.setObjectName("portLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.portLabel)
        self.portLineEdit = QtWidgets.QLineEdit(PLCCommSettingsDialog)
        self.portLineEdit.setObjectName("portLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.portLineEdit)
        self.comPortLabel = QtWidgets.QLabel(PLCCommSettingsDialog)
        self.comPortLabel.setObjectName("comPortLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.comPortLabel)
        self.comPortLineEdit = QtWidgets.QLineEdit(PLCCommSettingsDialog)
        self.comPortLineEdit.setObjectName("comPortLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comPortLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.savePushButton = QtWidgets.QPushButton(PLCCommSettingsDialog)
        self.savePushButton.setObjectName("savePushButton")
        self.buttonLayout.addWidget(self.savePushButton)
        self.cancelPushButton = QtWidgets.QPushButton(PLCCommSettingsDialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.buttonLayout.addWidget(self.cancelPushButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(PLCCommSettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(PLCCommSettingsDialog)

    def retranslateUi(self, PLCCommSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        PLCCommSettingsDialog.setWindowTitle(_translate("PLCCommSettingsDialog", "PLC Communication Settings"))
        self.commModeLabel.setText(_translate("PLCCommSettingsDialog", "Communication Mode:"))
        self.commModeComboBox.setItemText(0, _translate("PLCCommSettingsDialog", "RS485"))
        self.commModeComboBox.setItemText(1, _translate("PLCCommSettingsDialog", "TCP"))
        self.ipLabel.setText(_translate("PLCCommSettingsDialog", "IP Address:"))
        self.portLabel.setText(_translate("PLCCommSettingsDialog", "Port:"))
        self.comPortLabel.setText(_translate("PLCCommSettingsDialog", "COM Port:"))
        self.savePushButton.setText(_translate("PLCCommSettingsDialog", "Save"))
        self.cancelPushButton.setText(_translate("PLCCommSettingsDialog", "Cancel"))
