# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\DEV\Python\PLC Integration\src1-main\src1-main\RaspPiReader-master\RaspPiReader\qt\program_selection_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProgramSelectionForm(object):
    def setupUi(self, ProgramSelectionForm):
        ProgramSelectionForm.setObjectName("ProgramSelectionForm")
        ProgramSelectionForm.resize(500, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProgramSelectionForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.programLabel = QtWidgets.QLabel(ProgramSelectionForm)
        self.programLabel.setObjectName("programLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.programLabel)
        self.programComboBox = QtWidgets.QComboBox(ProgramSelectionForm)
        self.programComboBox.setObjectName("programComboBox")
        self.programComboBox.addItem("")
        self.programComboBox.addItem("")
        self.programComboBox.addItem("")
        self.programComboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.programComboBox)
        self.programInfoLabel = QtWidgets.QLabel(ProgramSelectionForm)
        self.programInfoLabel.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.programInfoLabel.setWordWrap(True)
        self.programInfoLabel.setStyleSheet("font-size: 12pt; color: #333333; border: 1px solid #CCCCCC; padding: 5px; background-color: #F9F9F9;")
        self.programInfoLabel.setObjectName("programInfoLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.programInfoLabel)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.startCycleButton = QtWidgets.QPushButton(ProgramSelectionForm)
        self.startCycleButton.setStyleSheet("background-color: #28a745; color: white; padding: 10px; border: none; border-radius: 4px;")
        self.startCycleButton.setObjectName("startCycleButton")
        self.buttonLayout.addWidget(self.startCycleButton)
        self.cancelButton = QtWidgets.QPushButton(ProgramSelectionForm)
        self.cancelButton.setStyleSheet("background-color: #dc3545; color: white; padding: 10px; border: none; border-radius: 4px;")
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(ProgramSelectionForm)
        QtCore.QMetaObject.connectSlotsByName(ProgramSelectionForm)

    def retranslateUi(self, ProgramSelectionForm):
        _translate = QtCore.QCoreApplication.translate
        ProgramSelectionForm.setWindowTitle(_translate("ProgramSelectionForm", "Select Program"))
        self.programLabel.setText(_translate("ProgramSelectionForm", "Select Program:"))
        self.programComboBox.setItemText(0, _translate("ProgramSelectionForm", "Program 1"))
        self.programComboBox.setItemText(1, _translate("ProgramSelectionForm", "Program 2"))
        self.programComboBox.setItemText(2, _translate("ProgramSelectionForm", "Program 3"))
        self.programComboBox.setItemText(3, _translate("ProgramSelectionForm", "Program 4"))
        self.programInfoLabel.setText(_translate("ProgramSelectionForm", "Program information will be displayed here."))
        self.startCycleButton.setText(_translate("ProgramSelectionForm", "Start Cycle"))
        self.cancelButton.setText(_translate("ProgramSelectionForm", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProgramSelectionForm = QtWidgets.QWidget()
    ui = Ui_ProgramSelectionForm()
    ui.setupUi(ProgramSelectionForm)
    ProgramSelectionForm.show()
    sys.exit(app.exec_())
