# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RaspPiReader/qt\serial_number_entry_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SerialNumberEntryForm(object):
    def setupUi(self, SerialNumberEntryForm):
        SerialNumberEntryForm.setObjectName("SerialNumberEntryForm")
        SerialNumberEntryForm.resize(600, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(SerialNumberEntryForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setObjectName("searchLayout")
        self.searchLineEdit = QtWidgets.QLineEdit(SerialNumberEntryForm)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.searchLayout.addWidget(self.searchLineEdit)
        self.searchButton = QtWidgets.QPushButton(SerialNumberEntryForm)
        self.searchButton.setObjectName("searchButton")
        self.searchLayout.addWidget(self.searchButton)
        self.verticalLayout.addLayout(self.searchLayout)
        self.serialTableWidget = QtWidgets.QTableWidget(SerialNumberEntryForm)
        self.serialTableWidget.setColumnCount(1)
        self.serialTableWidget.setRowCount(0)
        self.serialTableWidget.setHorizontalHeaderLabels(['Serial Number'])
        self.serialTableWidget.setObjectName("serialTableWidget")
        self.verticalLayout.addWidget(self.serialTableWidget)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.importExcelButton = QtWidgets.QPushButton(SerialNumberEntryForm)
        self.importExcelButton.setObjectName("importExcelButton")
        self.buttonLayout.addWidget(self.importExcelButton)
        self.nextButton = QtWidgets.QPushButton(SerialNumberEntryForm)
        self.nextButton.setObjectName("nextButton")
        self.buttonLayout.addWidget(self.nextButton)
        self.cancelButton = QtWidgets.QPushButton(SerialNumberEntryForm)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(SerialNumberEntryForm)
        QtCore.QMetaObject.connectSlotsByName(SerialNumberEntryForm)

    def retranslateUi(self, SerialNumberEntryForm):
        _translate = QtCore.QCoreApplication.translate
        SerialNumberEntryForm.setWindowTitle(_translate("SerialNumberEntryForm", "Enter Serial Numbers"))
        self.searchLineEdit.setPlaceholderText(_translate("SerialNumberEntryForm", "Search Serial Number..."))
        self.searchButton.setText(_translate("SerialNumberEntryForm", "Search"))
        self.importExcelButton.setText(_translate("SerialNumberEntryForm", "Import from Excel"))
        self.nextButton.setText(_translate("SerialNumberEntryForm", "Next"))
        self.cancelButton.setText(_translate("SerialNumberEntryForm", "Cancel"))
