# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\DEV\Python\PLC Integration\src1-main\src1-main\RaspPiReader-master\RaspPiReader\qt\serial_number_management.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SerialNumberManagementDialog(object):
    def setupUi(self, SerialNumberManagementDialog):
        SerialNumberManagementDialog.setObjectName("SerialNumberManagementDialog")
        SerialNumberManagementDialog.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(SerialNumberManagementDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.serialTableWidget = QtWidgets.QTableWidget(SerialNumberManagementDialog)
        self.serialTableWidget.setObjectName("serialTableWidget")
        self.serialTableWidget.setColumnCount(1)
        self.serialTableWidget.setRowCount(0)
        self.serialTableWidget.setHorizontalHeaderLabels(["Serial Number"])
        self.verticalLayout.addWidget(self.serialTableWidget)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.addButton = QtWidgets.QPushButton(SerialNumberManagementDialog)
        self.addButton.setObjectName("addButton")
        self.addButton.setText("Add")
        self.buttonLayout.addWidget(self.addButton)
        self.removeButton = QtWidgets.QPushButton(SerialNumberManagementDialog)
        self.removeButton.setObjectName("removeButton")
        self.removeButton.setText("Remove")
        self.buttonLayout.addWidget(self.removeButton)
        self.importButton = QtWidgets.QPushButton(SerialNumberManagementDialog)
        self.importButton.setObjectName("importButton")
        self.importButton.setText("Import")
        self.buttonLayout.addWidget(self.importButton)
        self.searchButton = QtWidgets.QPushButton(SerialNumberManagementDialog)
        self.searchButton.setObjectName("searchButton")
        self.searchButton.setText("Search")
        self.buttonLayout.addWidget(self.searchButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(SerialNumberManagementDialog)
        QtCore.QMetaObject.connectSlotsByName(SerialNumberManagementDialog)

    def retranslateUi(self, SerialNumberManagementDialog):
        _translate = QtCore.QCoreApplication.translate
        SerialNumberManagementDialog.setWindowTitle(_translate("SerialNumberManagementDialog", "Serial Number Management"))