# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RaspPiReader/qt/user_management.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserManagementDialog(object):
    def setupUi(self, UserManagementDialog):
        UserManagementDialog.setObjectName("UserManagementDialog")
        UserManagementDialog.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(UserManagementDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.userTableWidget = QtWidgets.QTableWidget(UserManagementDialog)
        self.userTableWidget.setColumnCount(4)
        self.userTableWidget.setRowCount(0)
        self.userTableWidget.setHorizontalHeaderLabels(['Username', 'Password', 'Settings', 'Search'])
        self.userTableWidget.setObjectName("userTableWidget")
        self.verticalLayout.addWidget(self.userTableWidget)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.addUserPushButton = QtWidgets.QPushButton(UserManagementDialog)
        self.addUserPushButton.setObjectName("addUserPushButton")
        self.buttonLayout.addWidget(self.addUserPushButton)
        self.editUserPushButton = QtWidgets.QPushButton(UserManagementDialog)
        self.editUserPushButton.setObjectName("editUserPushButton")
        self.buttonLayout.addWidget(self.editUserPushButton)
        self.removeUserPushButton = QtWidgets.QPushButton(UserManagementDialog)
        self.removeUserPushButton.setObjectName("removeUserPushButton")
        self.buttonLayout.addWidget(self.removeUserPushButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(UserManagementDialog)
        QtCore.QMetaObject.connectSlotsByName(UserManagementDialog)

    def retranslateUi(self, UserManagementDialog):
        _translate = QtCore.QCoreApplication.translate
        UserManagementDialog.setWindowTitle(_translate("UserManagementDialog", "User Management"))
        self.addUserPushButton.setText(_translate("UserManagementDialog", "Add User"))
        self.editUserPushButton.setText(_translate("UserManagementDialog", "Edit User"))
        self.removeUserPushButton.setText(_translate("UserManagementDialog", "Remove User"))
