# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RaspPiReader/qt/user_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserEditDialog(object):
    def setupUi(self, UserEditDialog):
        UserEditDialog.setObjectName("UserEditDialog")
        self.verticalLayout = QtWidgets.QVBoxLayout(UserEditDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.usernameLabel = QtWidgets.QLabel(UserEditDialog)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(UserEditDialog)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameLineEdit)
        self.passwordLabel = QtWidgets.QLabel(UserEditDialog)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(UserEditDialog)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.accessGrid = QtWidgets.QGridLayout()
        self.accessGrid.setObjectName("accessGrid")
        self.settingsCheckBox = QtWidgets.QCheckBox(UserEditDialog)
        self.settingsCheckBox.setObjectName("settingsCheckBox")
        self.accessGrid.addWidget(self.settingsCheckBox, 0, 0, 1, 1)
        self.searchCheckBox = QtWidgets.QCheckBox(UserEditDialog)
        self.searchCheckBox.setObjectName("searchCheckBox")
        self.accessGrid.addWidget(self.searchCheckBox, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.accessGrid)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.okPushButton = QtWidgets.QPushButton(UserEditDialog)
        self.okPushButton.setObjectName("okPushButton")
        self.buttonLayout.addWidget(self.okPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(UserEditDialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.buttonLayout.addWidget(self.cancelPushButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(UserEditDialog)
        QtCore.QMetaObject.connectSlotsByName(UserEditDialog)

    def retranslateUi(self, UserEditDialog):
        _translate = QtCore.QCoreApplication.translate
        UserEditDialog.setWindowTitle(_translate("UserEditDialog", "User Editor"))
        self.usernameLabel.setText(_translate("UserEditDialog", "Username:"))
        self.passwordLabel.setText(_translate("UserEditDialog", "Password:"))
        self.settingsCheckBox.setText(_translate("UserEditDialog", "Settings"))
        self.searchCheckBox.setText(_translate("UserEditDialog", "Search"))
        self.okPushButton.setText(_translate("UserEditDialog", "OK"))
        self.cancelPushButton.setText(_translate("UserEditDialog", "Cancel"))
