# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\DEV\Python\PLC Integration\src1-main\src1-main\RaspPiReader-master\RaspPiReader\qt\user_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserEditDialog(object):
    def setupUi(self, UserEditDialog):
        UserEditDialog.setObjectName("UserEditDialog")
        UserEditDialog.resize(400, 250)
        self.verticalLayout = QtWidgets.QVBoxLayout(UserEditDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.usernameLabel = QtWidgets.QLabel(UserEditDialog)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(UserEditDialog)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameLineEdit)
        self.passwordLabel = QtWidgets.QLabel(UserEditDialog)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(UserEditDialog)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        self.roleLabel = QtWidgets.QLabel(UserEditDialog)
        self.roleLabel.setObjectName("roleLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.roleLabel)
        self.roleLineEdit = QtWidgets.QLineEdit(UserEditDialog)
        self.roleLineEdit.setObjectName("roleLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.roleLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.okPushButton = QtWidgets.QPushButton(UserEditDialog)
        self.okPushButton.setObjectName("okPushButton")
        self.buttonLayout.addWidget(self.okPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(UserEditDialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.buttonLayout.addWidget(self.cancelPushButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(UserEditDialog)
        QtCore.QMetaObject.connectSlotsByName(UserEditDialog)

    def retranslateUi(self, UserEditDialog):
        _translate = QtCore.QCoreApplication.translate
        UserEditDialog.setWindowTitle(_translate("UserEditDialog", "User Editor"))
        self.usernameLabel.setText(_translate("UserEditDialog", "Username:"))
        self.passwordLabel.setText(_translate("UserEditDialog", "Password:"))
        self.roleLabel.setText(_translate("UserEditDialog", "Role:"))
        self.okPushButton.setText(_translate("UserEditDialog", "OK"))
        self.cancelPushButton.setText(_translate("UserEditDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserEditDialog = QtWidgets.QDialog()
    ui = Ui_UserEditDialog()
    ui.setupUi(UserEditDialog)
    UserEditDialog.show()
    sys.exit(app.exec_())
