# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RaspPiReader/qt\work_order_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WorkOrderForm(object):
    def setupUi(self, WorkOrderForm):
        WorkOrderForm.setObjectName("WorkOrderForm")
        WorkOrderForm.resize(342, 194)
        self.verticalLayout = QtWidgets.QVBoxLayout(WorkOrderForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.workOrderLabel = QtWidgets.QLabel(WorkOrderForm)
        self.workOrderLabel.setObjectName("workOrderLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.workOrderLabel)
        self.workOrderLineEdit = QtWidgets.QLineEdit(WorkOrderForm)
        self.workOrderLineEdit.setObjectName("workOrderLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.workOrderLineEdit)
        self.quantityLabel = QtWidgets.QLabel(WorkOrderForm)
        self.quantityLabel.setObjectName("quantityLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.quantityLabel)
        self.quantitySpinBox = QtWidgets.QSpinBox(WorkOrderForm)
        self.quantitySpinBox.setMaximum(250)
        self.quantitySpinBox.setObjectName("quantitySpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.quantitySpinBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.nextButton = QtWidgets.QPushButton(WorkOrderForm)
        self.nextButton.setObjectName("nextButton")
        self.buttonLayout.addWidget(self.nextButton)
        self.cancelButton = QtWidgets.QPushButton(WorkOrderForm)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(WorkOrderForm)
        QtCore.QMetaObject.connectSlotsByName(WorkOrderForm)

    def retranslateUi(self, WorkOrderForm):
        _translate = QtCore.QCoreApplication.translate
        WorkOrderForm.setWindowTitle(_translate("WorkOrderForm", "Enter Work Order"))
        self.workOrderLabel.setText(_translate("WorkOrderForm", "Work Order Number:"))
        self.quantityLabel.setText(_translate("WorkOrderForm", "Product Quantity:"))
        self.nextButton.setText(_translate("WorkOrderForm", "Next"))
        self.cancelButton.setText(_translate("WorkOrderForm", "Cancel"))
